
spring:
  profiles:
    active: dev
    
---

spring:
  config:
    activate:
      on-profile: dev
      
  flyway:
    enabled: true 
    
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/car_insurance
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
      