CREATE TABLE if not exists ORGANIZATION(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50),
	ADDRESS VARCHAR(100),
	PRIMARY KEY(ID)
);

CREATE TABLE if not exists EMPLOYEE(
	ID INT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(30),
	PASSWORD VARCHAR(100),
	FNAME VARCHAR(30),
	LNAME VARCHAR(30),
	MGR_ID INT,
	ORG_ID INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(MGR_ID) REFERENCES EMPLOYEE(ID),
	FOREIGN KEY(ORG_ID) REFERENCES ORGANIZATION(ID)
);

CREATE TABLE if not exists CLIENT(
	ID INT NOT NULL AUTO_INCREMENT,
	FNAME VARCHAR(30),
	LNAME VARCHAR(30),
	EMAIL VARCHAR(30),
	PASSWORD VARCHAR(100),
	ADDRESS VARCHAR(100),
	EMP_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE if not exists VEHICLE(
	VIN VARCHAR(100) NOT NULL,
	CLIENT_ID INT NOT NULL,
	MAKE VARCHAR(50),
	MODEL VARCHAR(50),
	YEAR INT,
	MILES INT,
	PLATE VARCHAR(10),
	PRIMARY KEY(VIN),
	FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID)
);

CREATE TABLE if not exists PAYMENT(
	ID INT NOT NULL AUTO_INCREMENT,
	CLIENT_ID INT NOT NULL,
	AMOUNT DOUBLE,
	DUE_DATE DATE,
	MISSED BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (ID),
	FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID)
);

CREATE TABLE if not exists CLAIM(
	ID INT NOT NULL AUTO_INCREMENT,
	CLAIM_DATE DATE,
	CLIENT_ID INT NOT NULL,
	VEHICLE_VIN VARCHAR(100),
	PRIMARY KEY(ID),
	FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID),
	FOREIGN KEY(VEHICLE_VIN) REFERENCES VEHICLE(VIN)
);